// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/solcates/grpc-istio-example/apis/rest/models"
)

// SayHelloAgainReader is a Reader for the SayHelloAgain structure.
type SayHelloAgainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SayHelloAgainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSayHelloAgainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSayHelloAgainOK creates a SayHelloAgainOK with default headers values
func NewSayHelloAgainOK() *SayHelloAgainOK {
	return &SayHelloAgainOK{}
}

/*SayHelloAgainOK handles this case with default header values.

A successful response.
*/
type SayHelloAgainOK struct {
	Payload *models.ApisHelloReply
}

func (o *SayHelloAgainOK) Error() string {
	return fmt.Sprintf("[GET /v1/helloagain][%d] sayHelloAgainOK  %+v", 200, o.Payload)
}

func (o *SayHelloAgainOK) GetPayload() *models.ApisHelloReply {
	return o.Payload
}

func (o *SayHelloAgainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApisHelloReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
