// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/solcates/grpc-istio-example/apis/rest/models"
)

// SayHelloReader is a Reader for the SayHello structure.
type SayHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SayHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSayHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSayHelloOK creates a SayHelloOK with default headers values
func NewSayHelloOK() *SayHelloOK {
	return &SayHelloOK{}
}

/*SayHelloOK handles this case with default header values.

A successful response.
*/
type SayHelloOK struct {
	Payload *models.ApisHelloReply
}

func (o *SayHelloOK) Error() string {
	return fmt.Sprintf("[GET /v1/hello][%d] sayHelloOK  %+v", 200, o.Payload)
}

func (o *SayHelloOK) GetPayload() *models.ApisHelloReply {
	return o.Payload
}

func (o *SayHelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApisHelloReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
