apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "grpc-istio-example.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
        helm.sh/chart: {{ include "grpc-istio-example.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            annotations:
                readiness.status.sidecar.istio.io/applicationPorts: ""
            labels:
                app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                        {{ if .Values.image.hash }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                        {{ else }}
                  image: "{{ .Values.image.repository }}@{{ .Values.image.hash }}"
                        {{end }}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}

                  args:
                      - server
                      - --debug
                  env:
                      - name: foo
                        value: bar
                  ports:
                      - name: http-rest
                        containerPort: {{.Values.pod.restPort}}
                        protocol: TCP
                      - name: grpc-grpc
                        containerPort: {{.Values.pod.grpcPort}}
                        protocol: TCP
                  livenessProbe:
                      exec:
                          command:
                              - /greeter
                              - client
                  readinessProbe:
                      exec:
                          command:
                              - /greeter
                              - client
                  resources:
                      limits:
                          cpu: 100m
                          memory: 128Mi
                      requests:
                          cpu: 100m
                          memory: 128Mi
