apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-istio-example.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
    helm.sh/chart: {{ include "grpc-istio-example.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc-greeter
      protocol: TCP
      name: grpc-greeter
    - port: {{ .Values.service.restPort }}
      targetPort: http-greeter
      protocol: TCP
      name: http-greeter
  selector:
    app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
