apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: {{ include "grpc-istio-example.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "grpc-istio-example.name" . }}
        helm.sh/chart: {{ include "grpc-istio-example.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    hosts:
        - "{{ .Values.host }}.{{ .Values.domain }}"
    gateways:
        - {{ include "grpc-istio-example.fullname" . }}
    http:
        - match:
              - port: {{ .Values.istio.grpcPort }}
          route:
              - destination:
                    port:
                        number: {{ .Values.service.grpcPort }}
                    host:  {{ include "grpc-istio-example.fullname" . }}
        - match:
              - port: {{ .Values.istio.restPort }}
          route:
              - destination:
                    port:
                        number: {{ .Values.service.restPort }}
                    host:  {{ include "grpc-istio-example.fullname" . }}